### PR TITLE
Extensible tuples

### PR DESCRIPTION
**Pull request by natefaubion**

### CODE REVIEW

**Comment by natefaubion** [comment]
I've gone ahead and made curry/uncurry open as well. This means that you can provide a larger tuple through `uncurryN`, and it only takes the arguments it needs. `curryN` also lets you provide the tail if the function requires a larger tuple. Closed currying then just becomes applying `unit` as the first argument. It's kind of like partial application from the right. We can switch these to closed, of course, but I thought it might be worth considering.

**Comment by garyb** [comment]
@paf31 I asked Nathan to go ahead and put this together since the work I did on re-associating the `Tuple`s still leaves the behaviour different from `Either`, in the sense of having combinators that allow accessing arbitrary positions without having to know the length of the nesting.

None of the libraries that depend on `tuples` have been updated yet, so it's no problem to release another version now and then proceed with the other updates.

**Comment by paf31** [comment]
Sorry, yes, looks good 😄

**Comment by garyb** [comment]
No problem, figured you wouldn't mind - just wanted to let you know what was going on!

**Pull request merged**
