### PR TITLE
cleaner nested tuple machinery

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by paf31** [comment]
Looks nice, but I'm not sure it's worth a breaking change and version bumps to whatever ridiculous number of libraries it is by now, to rename the `con*`s to `tuple`.

**Comment by jdegoes** [comment]
From a quick search, there are exactly zero libraries that use these functions in all of Github, so theoretically it is safe to not bump the major version.

**Comment by paf31** [comment]
:D Sounds good.

**Comment by paf31** [comment]
Apart from `purescript-echarts` apparently, but that has no reverse dependencies I assume.

**Comment by jdegoes** [comment]
echarts used to use it, but that code is gone now (AFAIK).

**Comment by joneshf** [comment]
Not all code is on github, and even if it were not all of it is public. Breaking changes are breaking changes for a reason. The versions should reflect that, **especially** in the core libraries.

**Comment by paf31** [comment]
Generally, I agree, but in this case, I've never heard of _anyone_ using this module. If I'm wrong and there are private repos, I'll moderate the complaints, but this wasn't damaging enough to motivate me to bump 20 or 30 major version numbers.

As we get closer to 1.0, I expect these sorts of things to slow down, and at 1.0, we can follow SV to the letter.

**Comment by jdegoes** [comment]
@joneshf Basically, it's pain for users or pain for us. Pre 1.0, I'd suggest the attitude be a bit more relaxed: there is a certainty bumping the minor version will incur massive pain for us, and some evidence to suggest that not bumping it will cause no pain for anyone (since Github is some sort of, perhaps biased, statistical sampling of the total source code using these libraries). Therefore it's better to not bump the version and apologize in the unlikely event that anyone is actually using it. 

I'd change my view post 1.0 or if there were any evidence of usage pre 1.0.

**Comment by garyb** [comment]
Hopefully we'll have script to help automate batch bumping-testing-releasing of dependencies soon.

**Comment by joneshf** [comment]
I'm not just picking nits here, this is a legitimate complaint.

I was using this, and it bit me in a project I updated at the wrong time. Then broke again this morning after the tag was replaced or whatever happened there.

From a user perspective, with the first tag nothing changed but the name. That's not worth a breaking patch version. With the second tag the semantics changed. A change in semantics is a fine breaking change, and worth a minor bump.

Nothing caught on fire, nothing was critical for safety, nothing crashed in production or whatever, so it's not that big a deal. But we don't live in a closed world, so we should always assume someone somewhere will be affected whether it's visible or not. I may be the only person affected, there may be more people later, or someone might have been bit by the `either` changes. In any case, pushing these issues onto the user of a library is not the right way.

**Comment by paf31** [comment]
I agree with you about what is the right way, and we just need a way to reduce the burden of pushing updates. Hopefully we can get a script together which can automate most of it, then this wouldn't be as much of an issue.

The other option is that we push a major version bump, and defer the updates of dependencies until it becomes an issue, but it seems like that would happen pretty quickly.

**Pull request merged**
