### PR TITLE
even nicer nested tuples

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by paf31** [comment]
:+1:

**Comment by hdgarrood** [comment]
I'm just wondering - why was this change made? Is there a reson to prefer nesting to the left rather than the right?

**Comment by jdegoes** [comment]
There are arguments for both. The left-nesting gives you proper instances (such as `Functor`) for all tuples.

**Comment by hdgarrood** [comment]
Ah, yes, of course. Thanks :)

**Pull request merged**
