### PR TITLE
add zipWithIndex

### PR DESCRIPTION
**Pull request by brainrape**
It was going to happen sooner or later.

### CODE REVIEW

**Comment by paf31** [comment]
I agree this is useful, but since you're probably going to `map` anyway, I'd argue that 

```purescript
zipWithIndex :: (a -> Number -> b) -> [a] -> [b]
```

would be more useful, added to `purescript-arrays`.

**Comment by brainrape** [comment]
[mapWithIndex](http://hackage.haskell.org/package/containers-0.5.6.3/docs/Data-Sequence.html#v:mapWithIndex) `:: (Number -> a -> b) -> [a] -> [b]` perhaps? 
That would belong in `purescript-foldable` or `purescript-array` ?

**Comment by brainrape** [comment]
`mapWithIndex` seems more useful, and `zipWithIndex` would just be `mapWithIndex (flip Tuple)`

`mapWithIndex` could be implemented as a `for` loop, like `map`, but also passing the index to the function

**Comment by paf31** [comment]
`mapWithIndex` sounds good. Adding it to `foldable` would be tricky though, unless it returned `f a -> [b]`.

**Pull request closed without merging**
